/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as ServiceRequestsRouteImport } from './routes/service-requests'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitorsIndexRouteImport } from './routes/visitors.index'
import { Route as ServiceRequestsIndexRouteImport } from './routes/service-requests.index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as VisitorsNewRouteImport } from './routes/visitors.new'
import { Route as VisitorsIdRouteImport } from './routes/visitors.$id'
import { Route as ServiceRequestsNewRouteImport } from './routes/service-requests.new'
import { Route as ServiceRequestsIdRouteImport } from './routes/service-requests.$id'
import { Route as ReservationsHallRouteImport } from './routes/reservations.hall'
import { Route as ReservationsBbqRouteImport } from './routes/reservations.bbq'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as PaymentsIdRouteImport } from './routes/payments.$id'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as ReservationsHallIndexRouteImport } from './routes/reservations.hall.index'
import { Route as ReservationsBbqIndexRouteImport } from './routes/reservations.bbq.index'
import { Route as ReservationsHallNewRouteImport } from './routes/reservations.hall.new'
import { Route as ReservationsBbqNewRouteImport } from './routes/reservations.bbq.new'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestsRoute = ServiceRequestsRouteImport.update({
  id: '/service-requests',
  path: '/service-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsIndexRoute = VisitorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisitorsRoute,
} as any)
const ServiceRequestsIndexRoute = ServiceRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRequestsRoute,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReservationsRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaymentsRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const VisitorsNewRoute = VisitorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VisitorsRoute,
} as any)
const VisitorsIdRoute = VisitorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VisitorsRoute,
} as any)
const ServiceRequestsNewRoute = ServiceRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ServiceRequestsRoute,
} as any)
const ServiceRequestsIdRoute = ServiceRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServiceRequestsRoute,
} as any)
const ReservationsHallRoute = ReservationsHallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => ReservationsRoute,
} as any)
const ReservationsBbqRoute = ReservationsBbqRouteImport.update({
  id: '/bbq',
  path: '/bbq',
  getParentRoute: () => ReservationsRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PaymentsIdRoute = PaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PaymentsRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const ReservationsHallIndexRoute = ReservationsHallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReservationsHallRoute,
} as any)
const ReservationsBbqIndexRoute = ReservationsBbqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReservationsBbqRoute,
} as any)
const ReservationsHallNewRoute = ReservationsHallNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReservationsHallRoute,
} as any)
const ReservationsBbqNewRoute = ReservationsBbqNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReservationsBbqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/payments': typeof PaymentsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reservations': typeof ReservationsRouteWithChildren
  '/service-requests': typeof ServiceRequestsRouteWithChildren
  '/visitors': typeof VisitorsRouteWithChildren
  '/news/$id': typeof NewsIdRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/reservations/bbq': typeof ReservationsBbqRouteWithChildren
  '/reservations/hall': typeof ReservationsHallRouteWithChildren
  '/service-requests/$id': typeof ServiceRequestsIdRoute
  '/service-requests/new': typeof ServiceRequestsNewRoute
  '/visitors/$id': typeof VisitorsIdRoute
  '/visitors/new': typeof VisitorsNewRoute
  '/news/': typeof NewsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/visitors/': typeof VisitorsIndexRoute
  '/reservations/bbq/new': typeof ReservationsBbqNewRoute
  '/reservations/hall/new': typeof ReservationsHallNewRoute
  '/reservations/bbq/': typeof ReservationsBbqIndexRoute
  '/reservations/hall/': typeof ReservationsHallIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/news/$id': typeof NewsIdRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/service-requests/$id': typeof ServiceRequestsIdRoute
  '/service-requests/new': typeof ServiceRequestsNewRoute
  '/visitors/$id': typeof VisitorsIdRoute
  '/visitors/new': typeof VisitorsNewRoute
  '/news': typeof NewsIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/service-requests': typeof ServiceRequestsIndexRoute
  '/visitors': typeof VisitorsIndexRoute
  '/reservations/bbq/new': typeof ReservationsBbqNewRoute
  '/reservations/hall/new': typeof ReservationsHallNewRoute
  '/reservations/bbq': typeof ReservationsBbqIndexRoute
  '/reservations/hall': typeof ReservationsHallIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/payments': typeof PaymentsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/reservations': typeof ReservationsRouteWithChildren
  '/service-requests': typeof ServiceRequestsRouteWithChildren
  '/visitors': typeof VisitorsRouteWithChildren
  '/news/$id': typeof NewsIdRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/reservations/bbq': typeof ReservationsBbqRouteWithChildren
  '/reservations/hall': typeof ReservationsHallRouteWithChildren
  '/service-requests/$id': typeof ServiceRequestsIdRoute
  '/service-requests/new': typeof ServiceRequestsNewRoute
  '/visitors/$id': typeof VisitorsIdRoute
  '/visitors/new': typeof VisitorsNewRoute
  '/news/': typeof NewsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/service-requests/': typeof ServiceRequestsIndexRoute
  '/visitors/': typeof VisitorsIndexRoute
  '/reservations/bbq/new': typeof ReservationsBbqNewRoute
  '/reservations/hall/new': typeof ReservationsHallNewRoute
  '/reservations/bbq/': typeof ReservationsBbqIndexRoute
  '/reservations/hall/': typeof ReservationsHallIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deliveries'
    | '/home'
    | '/login'
    | '/news'
    | '/payments'
    | '/profile'
    | '/reservations'
    | '/service-requests'
    | '/visitors'
    | '/news/$id'
    | '/payments/$id'
    | '/profile/edit'
    | '/reservations/bbq'
    | '/reservations/hall'
    | '/service-requests/$id'
    | '/service-requests/new'
    | '/visitors/$id'
    | '/visitors/new'
    | '/news/'
    | '/payments/'
    | '/profile/'
    | '/reservations/'
    | '/service-requests/'
    | '/visitors/'
    | '/reservations/bbq/new'
    | '/reservations/hall/new'
    | '/reservations/bbq/'
    | '/reservations/hall/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deliveries'
    | '/home'
    | '/login'
    | '/news/$id'
    | '/payments/$id'
    | '/profile/edit'
    | '/service-requests/$id'
    | '/service-requests/new'
    | '/visitors/$id'
    | '/visitors/new'
    | '/news'
    | '/payments'
    | '/profile'
    | '/reservations'
    | '/service-requests'
    | '/visitors'
    | '/reservations/bbq/new'
    | '/reservations/hall/new'
    | '/reservations/bbq'
    | '/reservations/hall'
  id:
    | '__root__'
    | '/'
    | '/deliveries'
    | '/home'
    | '/login'
    | '/news'
    | '/payments'
    | '/profile'
    | '/reservations'
    | '/service-requests'
    | '/visitors'
    | '/news/$id'
    | '/payments/$id'
    | '/profile/edit'
    | '/reservations/bbq'
    | '/reservations/hall'
    | '/service-requests/$id'
    | '/service-requests/new'
    | '/visitors/$id'
    | '/visitors/new'
    | '/news/'
    | '/payments/'
    | '/profile/'
    | '/reservations/'
    | '/service-requests/'
    | '/visitors/'
    | '/reservations/bbq/new'
    | '/reservations/hall/new'
    | '/reservations/bbq/'
    | '/reservations/hall/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveriesRoute: typeof DeliveriesRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  PaymentsRoute: typeof PaymentsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ReservationsRoute: typeof ReservationsRouteWithChildren
  ServiceRequestsRoute: typeof ServiceRequestsRouteWithChildren
  VisitorsRoute: typeof VisitorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-requests': {
      id: '/service-requests'
      path: '/service-requests'
      fullPath: '/service-requests'
      preLoaderRoute: typeof ServiceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors/': {
      id: '/visitors/'
      path: '/'
      fullPath: '/visitors/'
      preLoaderRoute: typeof VisitorsIndexRouteImport
      parentRoute: typeof VisitorsRoute
    }
    '/service-requests/': {
      id: '/service-requests/'
      path: '/'
      fullPath: '/service-requests/'
      preLoaderRoute: typeof ServiceRequestsIndexRouteImport
      parentRoute: typeof ServiceRequestsRoute
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/payments/': {
      id: '/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/visitors/new': {
      id: '/visitors/new'
      path: '/new'
      fullPath: '/visitors/new'
      preLoaderRoute: typeof VisitorsNewRouteImport
      parentRoute: typeof VisitorsRoute
    }
    '/visitors/$id': {
      id: '/visitors/$id'
      path: '/$id'
      fullPath: '/visitors/$id'
      preLoaderRoute: typeof VisitorsIdRouteImport
      parentRoute: typeof VisitorsRoute
    }
    '/service-requests/new': {
      id: '/service-requests/new'
      path: '/new'
      fullPath: '/service-requests/new'
      preLoaderRoute: typeof ServiceRequestsNewRouteImport
      parentRoute: typeof ServiceRequestsRoute
    }
    '/service-requests/$id': {
      id: '/service-requests/$id'
      path: '/$id'
      fullPath: '/service-requests/$id'
      preLoaderRoute: typeof ServiceRequestsIdRouteImport
      parentRoute: typeof ServiceRequestsRoute
    }
    '/reservations/hall': {
      id: '/reservations/hall'
      path: '/hall'
      fullPath: '/reservations/hall'
      preLoaderRoute: typeof ReservationsHallRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/reservations/bbq': {
      id: '/reservations/bbq'
      path: '/bbq'
      fullPath: '/reservations/bbq'
      preLoaderRoute: typeof ReservationsBbqRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/payments/$id': {
      id: '/payments/$id'
      path: '/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof PaymentsIdRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/reservations/hall/': {
      id: '/reservations/hall/'
      path: '/'
      fullPath: '/reservations/hall/'
      preLoaderRoute: typeof ReservationsHallIndexRouteImport
      parentRoute: typeof ReservationsHallRoute
    }
    '/reservations/bbq/': {
      id: '/reservations/bbq/'
      path: '/'
      fullPath: '/reservations/bbq/'
      preLoaderRoute: typeof ReservationsBbqIndexRouteImport
      parentRoute: typeof ReservationsBbqRoute
    }
    '/reservations/hall/new': {
      id: '/reservations/hall/new'
      path: '/new'
      fullPath: '/reservations/hall/new'
      preLoaderRoute: typeof ReservationsHallNewRouteImport
      parentRoute: typeof ReservationsHallRoute
    }
    '/reservations/bbq/new': {
      id: '/reservations/bbq/new'
      path: '/new'
      fullPath: '/reservations/bbq/new'
      preLoaderRoute: typeof ReservationsBbqNewRouteImport
      parentRoute: typeof ReservationsBbqRoute
    }
  }
}

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PaymentsRouteChildren {
  PaymentsIdRoute: typeof PaymentsIdRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsIdRoute: PaymentsIdRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ReservationsBbqRouteChildren {
  ReservationsBbqNewRoute: typeof ReservationsBbqNewRoute
  ReservationsBbqIndexRoute: typeof ReservationsBbqIndexRoute
}

const ReservationsBbqRouteChildren: ReservationsBbqRouteChildren = {
  ReservationsBbqNewRoute: ReservationsBbqNewRoute,
  ReservationsBbqIndexRoute: ReservationsBbqIndexRoute,
}

const ReservationsBbqRouteWithChildren = ReservationsBbqRoute._addFileChildren(
  ReservationsBbqRouteChildren,
)

interface ReservationsHallRouteChildren {
  ReservationsHallNewRoute: typeof ReservationsHallNewRoute
  ReservationsHallIndexRoute: typeof ReservationsHallIndexRoute
}

const ReservationsHallRouteChildren: ReservationsHallRouteChildren = {
  ReservationsHallNewRoute: ReservationsHallNewRoute,
  ReservationsHallIndexRoute: ReservationsHallIndexRoute,
}

const ReservationsHallRouteWithChildren =
  ReservationsHallRoute._addFileChildren(ReservationsHallRouteChildren)

interface ReservationsRouteChildren {
  ReservationsBbqRoute: typeof ReservationsBbqRouteWithChildren
  ReservationsHallRoute: typeof ReservationsHallRouteWithChildren
  ReservationsIndexRoute: typeof ReservationsIndexRoute
}

const ReservationsRouteChildren: ReservationsRouteChildren = {
  ReservationsBbqRoute: ReservationsBbqRouteWithChildren,
  ReservationsHallRoute: ReservationsHallRouteWithChildren,
  ReservationsIndexRoute: ReservationsIndexRoute,
}

const ReservationsRouteWithChildren = ReservationsRoute._addFileChildren(
  ReservationsRouteChildren,
)

interface ServiceRequestsRouteChildren {
  ServiceRequestsIdRoute: typeof ServiceRequestsIdRoute
  ServiceRequestsNewRoute: typeof ServiceRequestsNewRoute
  ServiceRequestsIndexRoute: typeof ServiceRequestsIndexRoute
}

const ServiceRequestsRouteChildren: ServiceRequestsRouteChildren = {
  ServiceRequestsIdRoute: ServiceRequestsIdRoute,
  ServiceRequestsNewRoute: ServiceRequestsNewRoute,
  ServiceRequestsIndexRoute: ServiceRequestsIndexRoute,
}

const ServiceRequestsRouteWithChildren = ServiceRequestsRoute._addFileChildren(
  ServiceRequestsRouteChildren,
)

interface VisitorsRouteChildren {
  VisitorsIdRoute: typeof VisitorsIdRoute
  VisitorsNewRoute: typeof VisitorsNewRoute
  VisitorsIndexRoute: typeof VisitorsIndexRoute
}

const VisitorsRouteChildren: VisitorsRouteChildren = {
  VisitorsIdRoute: VisitorsIdRoute,
  VisitorsNewRoute: VisitorsNewRoute,
  VisitorsIndexRoute: VisitorsIndexRoute,
}

const VisitorsRouteWithChildren = VisitorsRoute._addFileChildren(
  VisitorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveriesRoute: DeliveriesRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  PaymentsRoute: PaymentsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ReservationsRoute: ReservationsRouteWithChildren,
  ServiceRequestsRoute: ServiceRequestsRouteWithChildren,
  VisitorsRoute: VisitorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
